---
- name: Bootstrap
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: tls_ca
      tags: [tls_ca]
    - role: tls_certs
      tags: [tls_certs]
    - role: wait_for_connection
      tags: [wait_for_connection]
    - role: apt_sources
      tags: [apt_sources]
    - role: apt_packages
      apt_packages_add: '{{ apt_packages_bootstrap }}'
      tags: [apt_packages_bootstrap]
    - role: apt_upgrade
      tags: [apt_upgrade]
    - role: ini_config
      ini_config_files: '{{ ini_config_bootstrap }}'
      tags: [ini_config_bootstrap]

- name: Configuration
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: apt_packages
      tags: [apt_packages]
    - role: unarchive
      tags: [unarchive]
    - role: locale_gen
      tags: [locale_gen]
    - role: user
      tags: [user]
    - role: file
      tags: [file]
    - role: ini_config
      tags: [ini_config]
    - role: lineinfile
      tags: [lineinfile]
    - role: config
      tags: [config]

- name: Logs
  hosts: logs
  become: true
  gather_facts: false
  roles:
    - role: haproxy
      tags: [haproxy]
    - role: elasticsearch
      tags: [elasticsearch]
    - role: alertmanager
      tags: [alertmanager]

- name: Monitoring
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: filebeat
      tags: [filebeat]

- name: Core
  hosts: core
  become: true
  gather_facts: false
  roles:
    - role: ceph
      tags: [ceph]
    - role: radosgw_admin
      tags: [radosgw_admin]
    - role: etcd
      tags: [etcd]

- name: DB
  hosts: db
  become: true
  gather_facts: false
  roles:
    - role: patroni
      tags: [patroni]
    - role: patroni_db
      tags: [patroni_db]
    - role: redis
      tags: [redis]

- name: Redis sentinel
  hosts: core
  become: true
  gather_facts: false
  roles:
    - role: redis_sentinel
      tags: [redis_sentinel]

- name: Web
  hosts: web
  become: true
  gather_facts: false
  roles:
    - role: haproxy
      tags: [haproxy]
    - role: pgbouncer
      tags: [pgbouncer]
    - role: lineinfile
      lineinfile_files: '{{ lineinfile_s3fs }}'
      tags: [s3fs]
    - role: s3_bucket
      tags: [s3_bucket]
    - role: netbox
      tags: [netbox]
    - role: angie
      tags: [angie]
    - role: keepalived
      when: not yandex_cloud | default(false)
      tags: [keepalived]

- name: UI
  hosts: ui
  become: true
  gather_facts: false
  roles:
    - role: kibana
      tags: [kibana]
...
