---
- name: Update CA certificates
  ansible.builtin.copy:
    content: |
      {{ tls_copy_ca_content }}
    dest: '{{ tls_copy_ca_path }}'
    owner: '{{ tls_copy_cert_owner }}'
    group: '{{ tls_copy_cert_group }}'
    mode: '{{ tls_copy_cert_mode }}'
  diff: false
  loop: '{{ tls_copy_certs | ansible.builtin.dict2items }}'
  loop_control:
    label: '{{ item.key }}'
  no_log: '{{ not tls_copy_debug }}'
  notify: '{{ tls_copy_notify }}'

- name: Update certificates
  ansible.builtin.copy:
    content: |
      {{ tls_copy_cert_content }}
      {% if tls_copy_ca_chain %}
      {{ tls_copy_ca_content }}
      {% endif %}
      {% if tls_copy_key_chain %}
      {{ tls_copy_key_content }}
      {% endif %}
    dest: '{{ tls_copy_cert_path }}'
    owner: '{{ tls_copy_key_owner if tls_copy_key_chain
      else tls_copy_cert_owner }}'
    group: '{{ tls_copy_key_group if tls_copy_key_chain
      else tls_copy_cert_group }}'
    mode: '{{ tls_copy_key_mode if tls_copy_key_chain
      else tls_copy_cert_mode }}'
  diff: false
  loop: '{{ tls_copy_certs | ansible.builtin.dict2items }}'
  loop_control:
    label: '{{ item.key }}'
  no_log: '{{ not tls_copy_debug }}'
  notify: '{{ tls_copy_notify }}'
  when: tls_copy_cert_src is exists


- name: Update keys
  community.crypto.openssl_privatekey_convert:
    src_content: '{{ tls_copy_key_content }}'
    dest_path: '{{ tls_copy_key_path }}'
    format: '{{ tls_copy_key_format }}'
    owner: '{{ tls_copy_key_owner }}'
    group: '{{ tls_copy_key_group }}'
    mode: '{{ tls_copy_key_mode }}'
  no_log: '{{ not tls_copy_debug }}'
  diff: false
  loop: '{{ tls_copy_certs | ansible.builtin.dict2items }}'
  loop_control:
    label: '{{ item.key }}'
  notify: '{{ tls_copy_notify }}'
  when:
    - tls_copy_key_src is exists
    - not tls_copy_key_chain
...
