---
- name: Import certs role
  ansible.builtin.import_role:
    name: tls_copy
    public: false
  vars:
    tls_copy_certs: '{{ redis_sentinel_certs }}'
    tls_copy_key_owner: redis
    tls_copy_notify: Restart redis-sentinel service

- name: Import config role
  ansible.builtin.import_role:
    name: config
    public: false
  vars:
    config_content: '{{ redis_sentinel_config }}'
    config_notify: Restart redis-sentinel service

- name: Enable and start redis-sentinel service
  ansible.builtin.systemd_service:
    name: redis-sentinel.service
    enabled: true
    daemon_reload: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'

- name: Force all notified handlers to run
  ansible.builtin.meta: flush_handlers
...
