---
tls_ca_certs:
  alertmanager:
  alertmanager-gossip:
  angie:
  ceph-rgw:
  etcd:
  etcd-peer:
  elasticsearch:
  elasticsearch-transport:
  grafana:
  kibana:
  node_exporter:
  patroni:
  postgresql:
  redis:
  victoriametrics:
  vmstorage:
  web:

tls_certs_subject_alt_name:
  - 'DNS:{{ inventory_hostname_short }}'
  - 'DNS:localhost'
  - 'IP:{{ ip_address }}'
  - 'IP:127.0.0.1'
  - 'IP:127.0.0.2'
  - 'IP:127.0.0.3'
...
