---
config_content: '{{ {} | ansible.builtin.combine(*query(
  "ansible.builtin.vars", *query("ansible.builtin.varnames",
  "^config_content_.+"))) }}'
file_groups: '{{ query("ansible.builtin.vars", *query(
  "ansible.builtin.varnames", "^file_group_.+")) |
  ansible.builtin.flatten(1) }}'
ini_config_files: '{{ {} | ansible.builtin.combine(*query(
  "ansible.builtin.vars", *query("ansible.builtin.varnames",
  "^ini_config_file_.+"))) }}'
lineinfile_files: '{{ {} | ansible.builtin.combine(*query(
  "ansible.builtin.vars", *query("ansible.builtin.varnames",
  "^lineinfile_file_.+"))) }}'
user_add: '{{ {} | ansible.builtin.combine(*query(
  "ansible.builtin.vars", *query("ansible.builtin.varnames",
  "^user_add_.+"))) }}'
...
