---
apt_packages_add: '{{ apt_packages_add_default + apt_packages_add_override }}'
apt_packages_add_default:
  - bash-completion
  - chrony
  - filebeat
  - update-notifier-common
apt_packages_add_override: []
...
