---
apt_sources_add_override:
  redis: '{{ apt_sources_add_redis }}'
  postgresql: '{{ apt_sources_add_postgresql }}'

apt_packages_add_override:
  - acl
  - patroni
  - postgresql-{{ postgresql_version }}
  - redis-server
...
