---
lineinfile_file_redis:
  /root/.bashrc:
    - regexp: '^export REDISCLI_AUTH='
      line: export REDISCLI_AUTH='{{ redis_password }}'
    - regexp: '^alias redis-cli='
      line: alias redis-cli='redis-cli -h "${REDISCLI_HOST:-127.0.0.1}"
        -p "${REDISCLI_PORT:-6379}" --tls --cacert /etc/redis/redis-ca.crt
        --cert /etc/redis/redis.crt --key /etc/redis/redis.key'

redis_certs:
  redis: /etc/redis

redis_tls_ciphers:
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305
  - DHE-RSA-AES128-GCM-SHA256
  - DHE-RSA-AES256-GCM-SHA384
  - DHE-RSA-CHACHA20-POLY1305
redis_tls_ciphersuites:
  - TLS_AES_128_GCM_SHA256
  - TLS_AES_256_GCM_SHA384
  - TLS_CHACHA20_POLY1305_SHA256

redis_config:
  /etc/redis/dhparam:
    # https://ssl-config.mozilla.org/ffdhe2048.txt
    content: |
      -----BEGIN DH PARAMETERS-----
      MIIBCAKCAQEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
      +8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
      87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
      YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
      7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
      ssbzSibBsu/6iGtCOGEoXJf//////////wIBAg==
      -----END DH PARAMETERS-----
  /etc/redis/redis.conf:
    owner: redis
    mode: '0600'
    content: |
      # https://ssl-config.mozilla.org/#server=redis
      acllog-max-len 128
      activerehashing yes
      always-show-logo no
      aof-load-truncated yes
      aof-rewrite-incremental-fsync yes
      aof-timestamp-enabled no
      aof-use-rdb-preamble yes
      appenddirname "appendonlydir"
      appendfilename "appendonly.aof"
      appendfsync everysec
      appendonly yes
      auto-aof-rewrite-min-size 64mb
      auto-aof-rewrite-percentage 100
      bind 127.0.0.1 {{ ip_address }} -::1
      client-output-buffer-limit normal 0 0 0
      client-output-buffer-limit pubsub 32mb 8mb 60
      client-output-buffer-limit replica 256mb 64mb 60
      daemonize yes
      databases 16
      dbfilename dump.rdb
      dir /var/lib/redis
      disable-thp yes
      dynamic-hz yes
      hash-max-listpack-entries 512
      hash-max-listpack-value 64
      hll-sparse-max-bytes 3000
      hz 10
      jemalloc-bg-thread yes
      latency-monitor-threshold 0
      lazyfree-lazy-eviction no
      lazyfree-lazy-expire no
      lazyfree-lazy-server-del no
      lazyfree-lazy-user-del no
      lazyfree-lazy-user-flush no
      list-compress-depth 0
      list-max-listpack-size -2
      locale-collate ""
      logfile /var/log/redis/redis-server.log
      loglevel notice
      masterauth "{{ redis_password }}"
      no-appendfsync-on-rewrite no
      notify-keyspace-events ""
      oom-score-adj no
      oom-score-adj-values 0 200 800
      pidfile /run/redis/redis-server.pid
      port 0
      proc-title-template "{title} {listen-addr} {server-mode}"
      protected-mode yes
      rdb-del-sync-files no
      rdb-save-incremental-fsync yes
      rdbchecksum yes
      rdbcompression yes
      repl-disable-tcp-nodelay no
      repl-diskless-load disabled
      repl-diskless-sync yes
      repl-diskless-sync-delay 5
      repl-diskless-sync-max-replicas 0
      {% if inventory_hostname != redis_master %}
      replicaof {{ hostvars[redis_master].ip_address }} 6379
      {% endif %}
      replica-lazy-flush no
      replica-priority 100
      replica-read-only yes
      replica-serve-stale-data yes
      requirepass "{{ redis_password }}"
      set-max-intset-entries 512
      set-max-listpack-entries 128
      set-max-listpack-value 64
      set-proc-title yes
      slowlog-log-slower-than 10000
      slowlog-max-len 128
      stop-writes-on-bgsave-error yes
      stream-node-max-bytes 4096
      stream-node-max-entries 100
      supervised auto
      tcp-backlog 511
      tcp-keepalive 300
      timeout 0
      tls-auth-clients yes
      tls-ca-cert-file /etc/redis/redis-ca.crt
      tls-cert-file /etc/redis/redis.crt
      tls-ciphers {{ redis_tls_ciphers | join(':') }}
      tls-ciphersuites {{ redis_tls_ciphersuites | join(':') }}
      tls-cluster yes
      tls-dh-params-file /etc/redis/dhparam
      tls-key-file /etc/redis/redis.key
      tls-port 6379
      tls-prefer-server-ciphers no
      tls-protocols "TLSv1.2 TLSv1.3"
      tls-replication yes
      zset-max-listpack-entries 128
      zset-max-listpack-value 64
...
