---
user_add_ceph:
  ceph-admin:
    create_home: true
    home: /home/ceph-admin
    password: '!'
    update_password: on_create
    shell: /bin/bash
    system: false

ceph_osd_wait_count: 2

ceph_rgw_cert: '{{ lookup("ansible.builtin.file", ceph_rgw_cert_path) }}'
ceph_rgw_cert_path: ./secrets/ceph-rgw/{{ inventory_hostname }}.crt
ceph_rgw_key: '{{ lookup("ansible.builtin.file", ceph_rgw_key_path) }}'
ceph_rgw_key_path: ./secrets/ceph-rgw/{{ inventory_hostname }}.key

radosgw_admin_users:
  netbox: --display-name=netbox

ceph_config:
  /etc/sudoers.d/ceph-admin:
    content: |
      ceph-admin ALL=(ALL) NOPASSWD:ALL
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
    notify: []
  /etc/ceph/cluster-spec.yml:
    mode: '0600'
    content: |
      {% for host in groups['core'] %}
      {% set hvar = hostvars[host] %}
      ---
      service_type: host
      hostname: {{ host }}
      addr: {{ hvar.ip_address }}
      labels:
      - _admin
      - mon
      - mgr
      - rgw
      ...
      {% endfor %}
      ---
      service_type: crash
      placement:
        host_pattern: '*'
      ...
      ---
      service_type: mgr
      placement:
        label: mgr
      ...
      ---
      service_type: mon
      placement:
        label: mon
      ...
      {% for host in groups['core'] %}
      {% set hvar = hostvars[host] %}
      ---
      service_type: osd
      service_id: {{ host | replace('-', '_') }}
      placement:
        hosts:
        - {{ host }}
      config:
        osd_memory_target: 1073741824
        osd_memory_target_autotune: false
      spec:
        data_devices:
          all: true
      ...
      {% endfor %}
      ---
      service_type: rgw
      service_id: default
      placement:
        label: rgw
      networks:
        - 10.130.0.0/24
      config:
        rgw_cache_enabled: true
        rgw_cache_lru_size: 500
        rgw_thread_pool_size: 16
      spec:
        rgw_frontend_type: beast
        rgw_frontend_port: 443
        rgw_frontend_ssl_certificate: |
          {{ ceph_rgw_key | indent(4) }}
          {{ ceph_rgw_cert | indent(4) }}
        ssl: true
      ...
...
