---
apt_sources_add_override:
  ceph: '{{ apt_sources_add_ceph }}'
  redis: '{{ apt_sources_add_redis }}'
apt_packages_add_override:
  - ceph-common
  - cephadm
  - podman
  - lvm2
  - redis-sentinel
  - redis-server
...
