---
- name: Process file group paths
  ansible.builtin.file:
    path: '{{ item }}'
    src: '{{ filegroup.src | default(omit) }}'
    state: '{{ filegroup.state | default(omit) }}'
    owner: '{{ filegroup.owner | default(omit) }}'
    group: '{{ filegroup.group | default(omit) }}'
    mode: '{{ filegroup.mode | default(omit) }}'
  loop: '{{ filegroup.paths | default([]) }}'
...
