---
- name: Process configuration files
  ansible.builtin.include_tasks: file.yml
  loop: '{{ ini_config_files | ansible.builtin.dict2items }}'
  loop_control:
    label: '{{ file.key }}'
    loop_var: file
...
