---
file_groups_netbox:
  - paths:
      - /etc/netbox
      - /var/lib/netbox
    state: directory
    owner: root
    group: root
    mode: '0755'
  - paths: [/opt/netbox]
    src: /opt/netbox
    state: link

netbox_s3_access_key: '{{ netbox_s3_userinfo["keys"][0].access_key }}'
netbox_s3_secret_key: '{{ netbox_s3_userinfo["keys"][0].secret_key }}'
netbox_s3_userinfo: '{{ lookup("ansible.builtin.file",
  netbox_s3_userinfo_file) | ansible.builtin.from_json }}'
netbox_s3_userinfo_file: ./secrets/netbox_rgw_userinfo.json
netbox_version: '4.6.0'

user_add_netbox:
  netbox:

unarchive_urls_override:
  netbox.tar.gz:
    checksum: >-
      sha256:2060854d7a188d02bebdf9c437dfa3706b73b5e92966f467d96b877183d236d9
    creates: /opt/netbox-{{ netbox_version }}/upgrade.sh
    dest: /opt/
    extra_opts: []
    mode: null
    url: https://github.com/netbox-community/netbox/archive/refs/tags/v{{
      netbox_version }}.tar.gz
...
