---
apt_sources_add_override:
  angie: '{{ apt_sources_add_angie }}'
  postgresql: '{{ apt_sources_add_postgresql }}'
apt_packages_add_override:
  - angie
  - haproxy
  - keepalived
  - pgbouncer
  - postgresql-client-{{ postgresql_version }}
  - s3fs
  - telnet
  - python3
  - python3-pip
  - python3-venv
  - python3-dev
  - build-essential
  - libxml2-dev
  - libxslt1-dev
  - libffi-dev
  - libpq-dev
  - libssl-dev
  - zlib1g-dev

unarchive_urls_override:
  netbox.tar.gz:
    checksum: >-
      sha256:2060854d7a188d02bebdf9c437dfa3706b73b5e92966f467d96b877183d236d9
    creates: /opt/netbox-{{ netbox_version }}/upgrade.sh
    dest: /opt/
    extra_opts: []
    mode: null
    url: https://github.com/netbox-community/netbox/archive/refs/tags/v{{
      netbox_version }}.tar.gz
...
