---
s3_bucket_access_key: '{{ netbox_s3_access_key }}'
s3_bucket_secret_key: '{{ netbox_s3_secret_key }}'

s3_bucket_buckets:
  netbox-media:
    policy:
      Version: 2012-10-17
      Statement:
        - Sid: AnonymousPublicRead
          Effect: Allow
          Principal: '*'
          Action: ['s3:GetObject']
          Resource: ['arn:aws:s3:::netbox-media/*']
  netbox-scripts:
    policy:
      Version: 2012-10-17
      Statement:
        - Sid: AnonymousPublicRead
          Effect: Allow
          Principal: '*'
          Action: ['s3:GetObject']
          Resource: ['arn:aws:s3:::netbox-scripts/*']
...
