---
grafana_certs:
  grafana: /etc/grafana

grafana_file_groups:
  - paths: [/var/lib/grafana/dashboards]
    state: directory
    owner: root
    group: root
    mode: '0755'

grafana_admin_password: '{{ lookup("ansible.builtin.password",
  "secrets/grafana_password.txt", length=26) }}'

grafana_config:
  /etc/grafana/grafana.ini:
    owner: grafana
    mode: '0400'
    content: |
      app mode = production
      instance_name = {{ inventory_hostname }}

      [paths]
      data = /var/lib/grafana
      temp_data_lifetime = 24h
      logs = /var/log/grafana
      plugins = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning

      [server]
      protocol = https
      min_tls_version = TLS1.2
      http_addr = {{ ip_address }}
      http_port = 3000
      cert_file = /etc/grafana/grafana.crt
      cert_key = /etc/grafana/grafana.key

      [database]
      type = postgres
      url = postgres://grafana@/grafana?host=/var/run/postgresql&port=5432&binary_parameters=yes

      [security]
      admin_user = admin
      admin_password = {{ grafana_admin_password }}
  /etc/grafana/provisioning/datasources/prometheus.yml:
    content: |
      ---
      apiVersion: 1
      prune: true
      datasources:
        - name: prometheus
          type: prometheus
          access: proxy
          uid: r7zk34nql3okg4
          url: http://127.0.0.1:8481/select/0/prometheus
          isDefault: true
          editable: false
      ...
  /etc/grafana/provisioning/dashboards/dashboards.yml:
    content: |
      ---
      apiVersion: 1
      providers:
        - name: /var/lib/grafana/dashboards
          orgId: 1
          type: file
          disableDeletion: true
          updateIntervalSeconds: 10
          allowUiUpdates: false
          options:
            path: /var/lib/grafana/dashboards
            foldersFromFilesStructure: true
      ...

grafana_provisioning_dashboards:
  /var/lib/grafana/dashboards/alertmanager.json:
    content: '{{ lookup("ansible.builtin.file",
      "dashboards/alertmanager.json") }}'
  /var/lib/grafana/dashboards/angie.json:
    content: '{{ lookup("ansible.builtin.file",
      "dashboards/angie.json") }}'
  /var/lib/grafana/dashboards/node.json:
    content: '{{ lookup("ansible.builtin.file",
      "dashboards/node.json") }}'
  /var/lib/grafana/dashboards/vmagent.json:
    content: '{{ lookup("ansible.builtin.file",
      "dashboards/vmagent.json") }}'
  /var/lib/grafana/dashboards/vmalert.json:
    content: '{{ lookup("ansible.builtin.file",
      "dashboards/vmalert.json") }}'
  /var/lib/grafana/dashboards/vmcluster.json:
    content: '{{ lookup("ansible.builtin.file",
      "dashboards/vmcluster.json") }}'
...
