---
haproxy_certs:
  patroni: /etc/haproxy
  victoriametrics: /etc/haproxy

haproxy_stats_password: '{{ lookup("ansible.builtin.password",
  "secrets/haproxy_stats_password.txt", length=26, encrypt="sha512_crypt") }}'

# yamllint disable rule:line-length
haproxy_config:
  # https://ssl-config.mozilla.org/ffdhe2048.txt
  /etc/haproxy/dhparam:
    content: |
      -----BEGIN DH PARAMETERS-----
      MIIBCAKCAQEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
      +8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
      87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
      YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
      7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
      ssbzSibBsu/6iGtCOGEoXJf//////////wIBAg==
      -----END DH PARAMETERS-----
  /etc/haproxy/haproxy.cfg:
    mode: '0600'
    content: |
      global
        log /dev/log local0
        log /dev/log local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30000
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/haproxy
        crt-base /etc/haproxy

        # See: https://ssl-config.mozilla.org/#server=haproxy'
        ssl-default-bind-curves {{ haproxy_ssl_default_curves | join(":") }}
        ssl-default-bind-ciphers {{ haproxy_ssl_default_ciphers | join(":") }}
        ssl-default-bind-ciphersuites {{ haproxy_ssl_default_ciphersuites |
        join(":") }}
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets
        ssl-default-server-ciphers {{ haproxy_ssl_default_ciphers | join(":") }}
        ssl-default-server-ciphersuites {{ haproxy_ssl_default_ciphersuites |
        join(":") }}
        ssl-default-server-options ssl-min-ver TLSv1.2 no-tls-tickets
        ssl-dh-param-file /etc/haproxy/dhparam

        maxconn 400
      defaults
        log     global
        mode    tcp
        retries 2
        timeout connect 4s
        timeout client  30m
        timeout server  30m
        timeout check   1s
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http
      userlist stats
        user stats password {{ haproxy_stats_password }}
      listen stats
        mode http
        bind 127.0.0.1:7000
        bind [::1]:7000
        http-request auth unless { http_auth(stats) }
        stats enable
        stats uri /
      listen primary
        bind 127.0.0.1:5432
        bind [::1]:5432
        default-server inter 100 fall 3 rise 2 on-marked-down shutdown-sessions
      {% for server in groups['db'] %}
        server {{ server }} {{ hostvars[server].ip_address }}:5432 track patroni/{{ server }}
      {% endfor %}
      backend patroni
        mode http
        option httpchk
        http-check send meth OPTIONS uri /primary
        http-check expect status 200
        default-server inter 100 fall 3 rise 2 on-marked-down shutdown-sessions check ssl verify required ca-file "patroni-ca.crt" crt "patroni.crt"
      {% for server in groups['db'] %}
        server {{ server }} {{ hostvars[server].ip_address }}:8008
      {% endfor %}
      listen vmselect
        bind 127.0.0.1:8481
        bind [::1]:8481
        mode http
        option httpchk
        http-check send meth GET uri /health hdr Authorization "Basic {{
          ('victoria:' + haproxy_victoria_password) | ansible.builtin.b64encode
        }}"
        http-check expect status 200
        http-request set-header Authorization "Basic {{
          ('victoria:' + haproxy_victoria_password) | ansible.builtin.b64encode
        }}"
        default-server inter 1000 fall 3 rise 2 on-marked-down shutdown-sessions check check-ssl ssl verify required ca-file "victoriametrics-ca.crt" crt "victoriametrics.crt"
      {% for server in groups['logs'] %}
        server {{ server }} {{ hostvars[server].ip_address }}:8481
      {% endfor %}
...
