---
ceph_bootstrap_host: '{{ ansible_play_hosts_all | first }}'
ceph_bootstrap_mon_ip: '{{ ip_address }}'
ceph_bootstrap_args: --dashboard-password-noupdate --skip-monitoring-stack

ceph_config: {}
ceph_config_sections: {}

ceph_ssh_user: ceph-admin

ceph_dashboard_user: admin
ceph_dashboard_password: '{{ lookup("ansible.builtin.password",
  "secrets/ceph_dashboard_password.txt", length=26) }}'

ceph_cluster_spec_file: /etc/ceph/cluster-spec.yml

ceph_osd_wait_count: 1
ceph_osd_wait_delay: 30
ceph_osd_wait_retries: 30
...
