---
- name: Import certs role
  ansible.builtin.import_role:
    name: tls_copy
    public: false
  vars:
    tls_copy_certs: '{{ elasticsearch_certs }}'
    tls_copy_key_owner: elasticsearch
    tls_copy_notify: Restart elasticsearch service

- name: Import config role
  ansible.builtin.import_role:
    name: config
    public: false
  vars:
    config_content: '{{ elasticsearch_config }}'
    config_notify: Restart elasticsearch service

- name: Enable and start elasticsearch service
  ansible.builtin.systemd_service:
    name: elasticsearch.service
    daemon_reload: true
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'

- name: Setting elasticsearch users' passwords
  ansible.builtin.include_tasks: password.yml
  loop: '{{ elasticsearch_passwords |
    ansible.builtin.dict2items(key_name="name", value_name="password") }}'
  loop_control:
    label: '{{ user.name }}'
    loop_var: user
  no_log: '{{ not elasticsearch_debug }}'

- name: Force all notified handlers to run
  ansible.builtin.meta: flush_handlers
...
