---
- name: Get elasticsearch health for {{ user.name }}
  ansible.builtin.uri:
    url: '{{ elasticsearch_url }}/_cluster/health'
    url_username: '{{ user.name }}'
    url_password: '{{ user.password }}'
    force_basic_auth: true
    ca_path: '{{ elasticsearch_url_ca | default(omit, true) }}'
    client_cert: '{{ elasticsearch_url_cert | default(omit, true) }}'
    client_key: '{{ elasticsearch_url_key | default(omit, true) }}'
    validate_certs: '{{ elasticsearch_url_validate | default(omit, true) }}'
    status_code: [200, 401]
  no_log: '{{ not elasticsearch_debug }}'
  register: _elasticsearch_health

- name: Update user password for {{ user.name }}
  # noqa: risky-shell-pipe
  ansible.builtin.shell: >-
    yes {{ user.password | ansible.builtin.quote }}
    |
    /usr/share/elasticsearch/bin/elasticsearch-reset-password
    --batch
    --interactive
    --silent
    --username {{ user.name | ansible.builtin.quote }}
  changed_when: true
  no_log: '{{ not elasticsearch_debug }}'
  when: _elasticsearch_health.status == 401
...
