---
- name: Import config tasks
  ansible.builtin.import_tasks: config.yml

- name: Force all notified handlers to run
  ansible.builtin.meta: flush_handlers

- name: Import services tasks
  ansible.builtin.import_tasks: services.yml
...
