---
- name: Import unarchive role
  ansible.builtin.import_role:
    name: unarchive
    public: false
  vars:
    unarchive_urls: '{{ netbox_unarchive }}'
    unarchive_notify: Restart netbox service

- name: Import file role
  ansible.builtin.import_role:
    name: file
    public: false
  vars:
    file_groups: '{{ netbox_file_groups }}'

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml

- name: Force all notified handlers to run
  ansible.builtin.meta: flush_handlers

- name: Import services tasks
  ansible.builtin.import_tasks: services.yml
...
